library(foreign)
sample100 <- read.spss("sample100.sav")
summary(sample100)
str(sample100)
sample100 <- data.frame(sample100)
summary(sample100)
sample100 <- read.spss("sample100.por")
summary(sample100)
str(sample100)
sample100 <- data.frame(sample100)
summary(sample100)
pbc <- read.spss("pbc.sav")
summary(pbc)
str(pbc)
pbc <- data.frame(pbc)
summary(pbc)
pbc <- read.spss("pbcold.sav")
summary(pbc)
str(pbc)
pbc <- data.frame(pbc)
summary(pbc)
pbc <- read.spss("pbc.por")
summary(pbc)
str(pbc)
pbc <- data.frame(pbc)
summary(pbc)
q()
