library(foreign)
pc5 <- read.dta("pc5.dta")
summary(pc5)
str(pc5)
sun6 <- read.dta("sun6.dta")
summary(sun6)
str(sun6)
df<-read.dta("datefactor.dta")
summary(df)
data(esoph)
write.dta(esoph,esophile<-tempfile())
esoph2<-read.dta(esophile)
all.equal(ordered(esoph2$alcgp),esoph$alcgp)
write.dta(esoph,esophile,convert.factors="string")
esoph2<-read.dta(esophile)
all.equal(as.character(esoph$alcgp),esoph2$alcgp)
write.dta(esoph,esophile,convert.factors="code")
esoph2<-read.dta(esophile)
all.equal(as.numeric(esoph$alcgp),as.numeric(esoph2$alcgp))
q()
